# Generated by Django 4.2.2 on 2023-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
